### ISSUE TITLE
SyntaxError: Unexpected token =>

### ISSUE THREAD

**Issue by iamvlado** [hoetmaaiers/metalsmith-project-images#1]
Hi! Thank you for a wonderful plugin. Excellent work on the local machine. But there are some problems with travis-ci (https://travis-ci.org/iamvlado/metalsmith-tests).

```
/home/travis/build/iamvlado/metalsmith-tests/node_modules/metalsmith-project-images/src/index.js:36
         _.each (options, (optionsItem) => {
                                       ^^
SyntaxError: Unexpected token =>
```

You do not know why this happens?

**Comment by hoetmaaiers** [comment]
Hi this was a little bit of es6 syntax, used only on that line. Apparently the Travis CI test did not like it. Is it possible to use es6 syntax for Metalsmith plugins?

Anyway, it was only at that line I used es6 fat arrows, so I replaced it with the oldskool function in this commit https://github.com/hoetmaaiers/metalsmith-project-images/commit/c7e1b03d37a47eb543b43f95559f7731475a46c1. Can you (or can I) test it again in Travis?

Thank you for taking the time.

**Comment by hoetmaaiers** [comment]
Ok, after a quick search I added my own Travic CI integration. This should help the testing in 'metalsmith-tests'? In my Travis tests everything passes: https://travis-ci.org/hoetmaaiers/metalsmith-project-images ^^.

**Comment by iamvlado** [comment]
Awesome! Travis CI works great with old school function. Star and many thanks!
