### ISSUE TITLE
Make imagesDirectory optional

### ISSUE THREAD

**Issue by jvolker** [hoetmaaiers/metalsmith-project-images#4]
Currently the folder specified as `imagesDirectory` has to exist in every project / item of your pattern.

e.g.: 

```
.use(images({
    pattern: 'projects/**/*'
  }))
```

in every project there has to be a folder `images`. Otherwise you get an `Error: ENOENT: no such file or directory`

It would be great to be able to not have this folder, in case there are no images to the project.

**Comment by nianwang** [comment]
When the specified `imagesDirectory` does not exist, should the metadata array be added at all?

Instead, perhaps skip over those projects without the specified `imagesDirectory`.

There are two points to consider:
- An empty directory cannot exist with Git
- An empty directory with placeholder (e.g., `images/.placeholder`) will still result in an empty array already.

**Comment by nianwang** [comment]
Is it possible to update the release so this is picked up by NPM?

Reference: https://www.npmjs.com/package/metalsmith-project-images

**Comment by hoetmaaiers** [comment]
Valid question, bumped and pushed to v1.1.1.
