### ISSUE TITLE
Async version of fs.exists is used bu 'done' is already scheduled to be called

### ISSUE THREAD

**Issue by stakkata** [hoetmaaiers/metalsmith-project-images#7]
This causes the metalsmith pipeline to continue even when this step has not finished. This causes weird errors when the files parameter to the plugin is modified by other steps in the pipeline (e.g. md -> html):

...\node_modules\metalsmith-project-images\src\index.js:67
      files[file][options.imagesKey] = files[file][options.imagesKey] || [];
                                                  ^
TypeError: Cannot read property 'images' of undefined

Use fs.existsSync on line 55 instead.

**Comment by hoetmaaiers** [comment]
Would you mind sending a pull request?

**Comment by edwardessing** [comment]
I'm also getting this! ):

**Comment by hoetmaaiers** [comment]
@stakkata I see you already forked this repo and made the assent changes. Are the changes ready for a pull request?

**Comment by stakkata** [comment]
@hoetmaaiers Sorry, it is the first time I'm using github. I'm currently not familiar with the "normal" workflow. Nevertheless I created a pull request from the fork. I hope that's what you expected?

**Comment by hoetmaaiers** [comment]
Exactly what I was aiming for. Thank you 👏 !

**Comment by edwardessing** [comment]
Sorry still getting this issue...

**Comment by hoetmaaiers** [comment]
Hi @edwardessing , I did not publish the latest version 1.1.2 to npm, my bad. Make sure to install version the latest version from https://www.npmjs.com/package/metalsmith-project-images. This will include your PR!
