### ISSUE TITLE
Post all images in a directory and its subdirectories

### ISSUE THREAD

**Issue by edwardessing** [hoetmaaiers/metalsmith-project-images#9]
If I have a fold structure like so:
`|  images/`
`|       |-- image-1.png`
`|       |-- image-2.png`
`|       |-- more-images/`
`|       |--    |-- image-3.png`
`|       |--    |-- image-4.png`

...is there a way I can post all images at once with the same call?

**Comment by hoetmaaiers** [comment]
no sorry, the project / image structure is limited to:

` project-a/`
`      |-- images/`
`      |--    |-- image-1.png`
`      |--    |-- image-2.png`
` project-b/`
`      |-- images/`
`      |--    |-- image-3.png`
`      |--    |-- image-4.png`
